/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/TBSpulWiKQ0
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export function AuthorPage() {
  return (
    <div className="flex flex-col items-center justify-center px-4 py-6 md:px-6 lg:py-16 md:py-12">
      <div className="flex flex-col items-center space-y-4">
        <Avatar className="w-24 h-24">
          <AvatarImage alt="Author's name" src="/placeholder-avatar.jpg" />
          <AvatarFallback>AN</AvatarFallback>
        </Avatar>
        <h1 className="text-2xl font-bold">Author's Name</h1>
        <p className="text-center text-gray-500 dark:text-gray-400">
          Author's bio goes here. This is a short introduction about the author.
        </p>
        <Button>Follow</Button>
        <div className="flex gap-4">
          <Link href="#">
            <TwitterIcon className="w-6 h-6" />
          </Link>
          <Link href="#">
            <FacebookIcon className="w-6 h-6" />
          </Link>
          <Link href="#">
            <InstagramIcon className="w-6 h-6" />
          </Link>
        </div>
      </div>
      <div className="w-full max-w-2xl mx-auto mt-12 space-y-6">
        <h2 className="text-xl font-bold">Published Articles</h2>
        <div className="space-y-4">
          <div className="flex flex-col space-y-2">
            <h3 className="text-lg font-semibold">Article Title 1</h3>
            <p className="text-gray-500 dark:text-gray-400">
              Published on January 1, 2024
            </p>
          </div>
          <div className="flex flex-col space-y-2">
            <h3 className="text-lg font-semibold">Article Title 2</h3>
            <p className="text-gray-500 dark:text-gray-400">
              Published on February 1, 2024
            </p>
          </div>
          <div className="flex flex-col space-y-2">
            <h3 className="text-lg font-semibold">Article Title 3</h3>
            <p className="text-gray-500 dark:text-gray-400">
              Published on March 1, 2024
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

function TwitterIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  );
}

function FacebookIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 1-1h3z" />
    </svg>
  );
}

function InstagramIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 12.63 8 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  );
}
