/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/9eyP6onzz2W
 */
import Link from "next/link"

export function BlogsList() {
  return (
    <div className="grid md:grid-cols-[240px_1fr] gap-4 px-4 md:px-6 py-6">
      <aside className="space-y-4">
        <h2 className="text-lg font-semibold">Categories</h2>
        <ul className="space-y-2">
          <li>
            <Link className="text-sm font-medium hover:underline" href="#">
              Technology
            </Link>
          </li>
          <li>
            <Link className="text-sm font-medium hover:underline" href="#">
              Business
            </Link>
          </li>
          <li>
            <Link className="text-sm font-medium hover:underline" href="#">
              Lifestyle
            </Link>
          </li>
          <li>
            <Link className="text-sm font-medium hover:underline" href="#">
              Travel
            </Link>
          </li>
          <li>
            <Link className="text-sm font-medium hover:underline" href="#">
              Health
            </Link>
          </li>
        </ul>
      </aside>
      <main className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        <article>
          <Link className="block aspect-content aspect-16/9 rounded-lg overflow-hidden" href="#">
            <img
              alt="Blog post cover"
              className="object-cover"
              height={280}
              src="/placeholder.svg"
              style={{
                aspectRatio: "500/280",
                objectFit: "cover",
              }}
              width={500}
            />
          </Link>
          <h2 className="mt-4 text-lg font-semibold">
            <Link className="hover:underline" href="#">
              The Future of Technology
            </Link>
          </h2>
          <p className="text-sm text-gray-500">By John Doe, January 1, 2024</p>
        </article>
        <article>
          <Link className="block aspect-content aspect-16/9 rounded-lg overflow-hidden" href="#">
            <img
              alt="Blog post cover"
              className="object-cover"
              height={280}
              src="/placeholder.svg"
              style={{
                aspectRatio: "500/280",
                objectFit: "cover",
              }}
              width={500}
            />
          </Link>
          <h2 className="mt-4 text-lg font-semibold">
            <Link className="hover:underline" href="#">
              Business Trends in 2024
            </Link>
          </h2>
          <p className="text-sm text-gray-500">By Jane Smith, February 1, 2024</p>
        </article>
        <article>
          <Link className="block aspect-content aspect-16/9 rounded-lg overflow-hidden" href="#">
            <img
              alt="Blog post cover"
              className="object-cover"
              height={280}
              src="/placeholder.svg"
              style={{
                aspectRatio: "500/280",
                objectFit: "cover",
              }}
              width={500}
            />
          </Link>
          <h2 className="mt-4 text-lg font-semibold">
            <Link className="hover:underline" href="#">
              Living a Healthy Lifestyle
            </Link>
          </h2>
          <p className="text-sm text-gray-500">By Alex Johnson, March 1, 2024</p>
        </article>
        <article>
          <Link className="block aspect-content aspect-16/9 rounded-lg overflow-hidden" href="#">
            <img
              alt="Blog post cover"
              className="object-cover"
              height={280}
              src="/placeholder.svg"
              style={{
                aspectRatio: "500/280",
                objectFit: "cover",
              }}
              width={500}
            />
          </Link>
          <h2 className="mt-4 text-lg font-semibold">
            <Link className="hover:underline" href="#">
              Exploring the World: Top Travel Destinations
            </Link>
          </h2>
          <p className="text-sm text-gray-500">By Sarah Lee, April 1, 2024</p>
        </article>
      </main>
    </div>
  )
}
