/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/TMzFbw3OqKX
 */
import Link from "next/link";

export function BlogPage() {
  return (
    <main className="px-4 py-6 md:px-6 md:py-12 lg:py-16">
      <article className="prose prose-gray max-w-6xl mx-auto dark:prose-invert">
        <img
          alt="Cover image"
          className="aspect-video overflow-hidden rounded-lg object-cover"
          height="340"
          src="/placeholder.svg"
          width="1250"
        />
        <div className="space-y-2 not-prose">
          <h1 className="text-4xl font-extrabold tracking-tight lg:text-5xl">
            The Journey of AI: From Turing to Modern Day
          </h1>
          <p className="text-gray-500 dark:text-gray-400">
            Posted on February 3, 2024
          </p>
        </div>
        <p>
          Artificial Intelligence (AI) has been a fascinating concept of science
          fiction for decades, but many researchers think we’re finally getting
          close to making AI a reality.
        </p>
        <p>
          The journey of AI from its inception to the modern day has been filled
          with ups and downs, successes and failures. But through it all, the
          idea of creating an intelligent machine has remained a constant
          fascination.
        </p>
        <p>
          In this article, we'll explore the history of AI, from the early days
          of Turing to the sophisticated AI technologies of today.
        </p>
        <div className="mt-4 space-x-2">
          <Link
            className="inline-flex items-center px-3 py-0.5 rounded-full text-sm font-medium bg-indigo-100 text-indigo-800"
            href="#"
          >
            #AI
          </Link>
          <Link
            className="inline-flex items-center px-3 py-0.5 rounded-full text-sm font-medium bg-indigo-100 text-indigo-800"
            href="#"
          >
            #History
          </Link>
          <Link
            className="inline-flex items-center px-3 py-0.5 rounded-full text-sm font-medium bg-indigo-100 text-indigo-800"
            href="#"
          >
            #Technology
          </Link>
        </div>
      </article>
    </main>
  );
}
