/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/SN1MWP6QY8w
 */
import Link from "next/link";

export function LandingPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="relative h-[600px]">
        <img
          alt="Background"
          className="absolute inset-0 object-cover w-full h-full"
          height="600"
          src="/placeholder.svg"
          style={{
            aspectRatio: "1200/600",
            objectFit: "cover",
          }}
          width="1200"
        />
        <div className="relative z-10 flex flex-col items-center justify-center h-full px-4 text-center text-white bg-black bg-opacity-50">
          <h1 className="text-4xl font-bold sm:text-5xl md:text-6xl">
            Welcome to Our Platform
          </h1>
          <p className="mt-4 text-lg sm:text-xl md:text-2xl">
            Join us and explore our features
          </p>
          <Link
            className="inline-flex mt-8 px-6 py-3 text-base font-medium text-black bg-white rounded-md hover:bg-gray-200"
            href="#"
          >
            Get Started
          </Link>
        </div>
      </header>
      <header className="bg-gray-800 text-white">
        <div className="container mx-auto flex justify-between items-center p-6">
          <h2 className="font-bold text-xl">Our Platform</h2>
          <nav className="flex space-x-4">
            <Link className="hover:text-gray-300" href="#">
              Home
            </Link>
            <Link className="hover:text-gray-300" href="#">
              About
            </Link>
            <Link className="hover:text-gray-300" href="#">
              Services
            </Link>
            <Link className="hover:text-gray-300" href="#">
              Contact
            </Link>
          </nav>
        </div>
      </header>
      <main className="flex-1 py-12 bg-white">
        <div className="container px-4 mx-auto">
          <h2 className="text-3xl font-bold text-center">Our Features</h2>
          <div className="grid gap-8 mt-8 md:grid-cols-3">
            <div className="flex flex-col items-center p-6 bg-gray-100 rounded-lg">
              <GlobeIcon className="w-12 h-12 mb-4" />
              <h3 className="text-xl font-bold">Global Access</h3>
              <p className="mt-2 text-center">
                Access our platform from anywhere in the world.
              </p>
            </div>
            <div className="flex flex-col items-center p-6 bg-gray-100 rounded-lg">
              <ClockIcon className="w-12 h-12 mb-4" />
              <h3 className="text-xl font-bold">24/7 Support</h3>
              <p className="mt-2 text-center">
                We're here to help, day or night.
              </p>
            </div>
            <div className="flex flex-col items-center p-6 bg-gray-100 rounded-lg">
              <ShieldIcon className="w-12 h-12 mb-4" />
              <h3 className="text-xl font-bold">Secure and Reliable</h3>
              <p className="mt-2 text-center">Your data is safe with us.</p>
            </div>
          </div>
        </div>
      </main>
      <footer className="py-6 bg-gray-800">
        <div className="container flex flex-col items-center justify-between px-4 sm:flex-row">
          <div className="flex space-x-8">
            <Link className="text-gray-300 hover:text-white" href="#">
              Facebook
            </Link>
            <Link className="text-gray-300 hover:text-white" href="#">
              Twitter
            </Link>
            <Link className="text-gray-300 hover:text-white" href="#">
              Instagram
            </Link>
          </div>
          <p className="mt-4 text-sm text-gray-300 sm:mt-0">
            © 2024 Our Platform. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}

function GlobeIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <line x1="2" x2="22" y1="12" y2="12" />
      <path d="M12 2a15.3 15.3 0 1 4 10 1-4 1-4-10 4-10z" />
    </svg>
  );
}

function ClockIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 16 14" />
    </svg>
  );
}

function ShieldIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10" />
    </svg>
  );
}
